{{- if and ( .Values.prometheus.serviceMonitor.enabled ) (.Values.prometheus.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{- include "promitor-agent-resource-discovery.labels" . | nindent 4 }}
{{- if .Values.prometheus.serviceMonitor.labels }}
{{ toYaml .Values.prometheus.serviceMonitor.labels | indent 4 }}
{{- end }}
  name: {{ template "promitor-agent-resource-discovery.fullname" . }}
{{- if .Values.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
{{- end }}
spec:
  endpoints:
  - targetPort: http
{{- if .Values.prometheus.serviceMonitor.interval }}
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
{{- end }}
{{- if .Values.prometheus.serviceMonitor.timeout }}
    scrapeTimeout: {{ .Values.prometheus.serviceMonitor.timeout }}
{{- end }}
  jobLabel: {{ template "promitor-agent-resource-discovery.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "promitor-agent-resource-discovery.selectorLabels" . | nindent 6 }}
{{- end }}
