{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "promitor-agent-scraper.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-scraper.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.azureAuthentication.identity.key}}
  {{ .Values.secrets.appKeySecret  }}: {{ .Values.azureAuthentication.identity.key | b64enc | quote }}
  {{- else if .Values.azureAuthentication.appKey}}
  {{ .Values.secrets.appKeySecret  }}: {{ .Values.azureAuthentication.appKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.metricSinks.atlassianStatuspage.apiKey }}
  {{ .Values.secrets.atlassianStatuspageApiKey }}: {{ .Values.metricSinks.atlassianStatuspage.apiKey | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
