apiVersion: v2
version: 2.4.2
appVersion: 2.3.0
type: application
name: promitor-agent-scraper
description: Promitor, bringing Azure Monitor metrics where you need them.
home: https://promitor.io
sources:
  - https://github.com/tomkerkhove/promitor
  - https://github.com/promitor/charts
maintainers:
  - name: Tom Kerkhove
    url: https://github.com/tomkerkhove
icon: https://raw.githubusercontent.com/tomkerkhove/promitor/master/docs/media/logos/promitor.png
