name: Helm Chart CI - Resource Discovery Agent

on:
  pull_request:
    paths:
    - '.github/workflows/ci-agent-resource-discovery.yml'
    - 'promitor-agent-resource-discovery/**'

jobs:
  lint-helm-3-x:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Helm install
      uses: Azure/setup-helm@v1

    - name: Lint Promitor Resource Discovery Helm chart
      run: helm lint promitor-agent-resource-discovery --values examples/promitor-agent-resource-discovery.config.yaml

  deploy-helm-3-x:
    name: Deploy chart to Kind cluster
    needs: [lint-helm-3-x]
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Helm install
      uses: Azure/setup-helm@v1

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.0.0

    - name: Show Kubernetes version
      run: |
        kubectl version

    - name: Show Helm version
      run: |
        helm version

    - name: Create Promitor namespace
      run: kubectl create ns promitor

    - name: Template Helm chart
      run: helm template promitor-agent-resource-discovery ./promitor-agent-resource-discovery/ --namespace promitor --values examples/promitor-agent-resource-discovery.config.yaml

    - name: Install Helm chart
      run: helm install promitor-agent-resource-discovery ./promitor-agent-resource-discovery/ --namespace promitor --values examples/promitor-agent-resource-discovery.config.yaml
